players_info = {
    "seeded_players_md": [
        "Amit / Kairav [1]",
        "Manish / Jiten [2]",
        "Kartik / Deepak [3]",
        "Manoj / Abhay [4]",
        "Jatin / Pranit [5]",
        "Madhav / Mahesh [6]",
        "Satwik / Vihaan [7]",
        "Himanshu / Giri [8]",
        "Bala / Pranav [9]",
        "Parth / Abhishek [10]",
        "Rohit / Sandeep [11]",
        "Ankur / Nilesh [12]",
        "Siva / Nishant [13]",
        "Ravi / Sameer [14]",
        "Harsh / Mahboob [15]",
        "Arjun / Tushar [16]"
    ],
    "unseeded_players_md": [
        "Akash / Darshan",
        "Chetan / Ramandeep",
        "Vikas / Saurabh",
        "Shubham / Aditya",
        "Rohan / Tanmay",
        "Tejas / Kunal",
        "Ashish / Devendra",
        "Chirag / Mayank",
        "Puneet / Tarun",
        "Sanket / Vipul",
        "Ajay / Lokesh",
        "Uday / Milan",
        "Gagan / Harish",
        "Yash / Omkar",
        "Sahil / Deepesh",
        "Varun / Dheeraj"
    ],
    "unseeded_players_extra_md":[
        "Rehan / Joseph",
        "Arvind / Aman",
        "Nitin / Arunesh",
        "Roshan / Kevin",
        "Raghunath / Sai Venkat",
        "Hassan / Kuldeep",
        "Farhan / Satyam",
        "Shashank / Vivek",
        "Vikram / Alan",
        "Yogesh / Vishesh"
    ],
    "seeded_players_wd": [
        "Pranali / Neha [1]",
        "Prakriti / Aarohi [2]",
        "Smriti / Richa [3]",
        "Jenny / Trisha [4]",
        "Vanshika / Kriti [5]",
        "Namita / Prerna [6]",
        "Mughda / Breesha [7]",
        "Avika / Anjali [8]",
        "Samaira / Naina [9]",
        "Tara / Riya [10]",
        "Priya / Falak [11]",
        "Tanisha / Ira [12]",
        "Megha / Shreya [13]",
        "Khushi / Diya [14]",
        "Ankita / Suhani [15]",
        "Aastha / Ishita [16]"
    ],
    "unseeded_players_wd": [
        "Harshita / Pallavi",
        "Sanya / Mitali",
        "Simran / Payal",
        "Muskaan / Bhavya",
        "Divya / Kritisha",
        "Parul / Meera",
        "Charvi / Sneha",
        "Kashish / Rupali",
        "Radhika / Tanishka",
        "Komal / Mahima",
        "Swati / Deeksha",
        "Rekha / Aparna",
        "Kirti / Vaishnavi",
        "Pooja / Amrita",
        "Shivangi / Garima",
        "Navya / Aayushi"
    ],
    "unseeded_players_extra_wd":[
        "Mariam / Kavya",
        "Prachi / Keerthana",
        "Aishwarya / Poonam",
        "Chavvi / Divyanka",
        "Ishika / Fatima",
        "Mayuri / Shalini",
        "Preethi / Revathi",
        "Sana / Tanuja",
        "Purva / Soumya",
        "Vedhika / Shikha"
    ],
    "seeded_players_xd": [
        "Aarushi / Aarav [1]",
        "Samaira / Manav [2]",
        "Naina / Siddharth [3]",
        "Tara / Kabir [4]",
        "Misha / Samar [5]",
        "Niharika / Sreenivas [6]",
        "Riya / Nehal [7]",
        "Himani / Ishaan [8]",
        "Nishika / Raghu [9]",
        "Shruti / Kartik [10]",
        "Prakriti / Manish [11]",
        "Joyce / Deepak [12]",
        "Tanishka / Kairav [13]",
        "Namita / Abhinav [14]",
        "Avani / Mahesh [15]",
        "Rivya / Vihaan [16]"
    ],
    "unseeded_players_xd": [
        "Avika / Parth",
        "Anika / Abhishek",
        "Priya / Ritesh",
        "Sonali / Mayur",
        "Falak / Samarth",
        "Ira / Ishant",
        "Kashvi / Priyank",
        "Sara / Mohit",
        "Khushi / Jatin",
        "Tia / Rachit",
        "Shreya / Amit",
        "Navya / Tejas",
        "Pankhuri / Jiten",
        "Aastha / Pranav",
        "Shikha / Madhav",
        "Megha / Satwik"
    ],
    "unseeded_players_extra_xd":[
        "Shalini / Vignesh",
        "Tanya / Alan",
        "Keerthana / Pratyush",
        "Roshni / Rehan",
        "Tanuja / Rajat",
        "Malvika / Roshan",
        "Shambhavi / Vishesh",
        "Diya / Jay",
        "Kashish / Nitin",
        "Fatima / Pratik"
    ]
}
